version: "3.4"

services:

  ### MongoDB Server #####################################
  mongo:
    image: mongo:4.0.5
    ports:
      - "27017:27017"
    environment:
      - TZ=Europe/Berlin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb:/data/db

  ### MongoDB UI #####################################
  mongo-ui:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongo

volumes:
  mongodb:
    driver: "local"
