package http

import (
	"context"

	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"
	"github.com/lukasjarosch/microservice-structure/pkg/config"
)

// GatewayHandler is a convenience-type. It has the same signature as the generated
// functions of the grpc-gateway plugin
type GatewayHandler func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error

// Gateway is an abstraction for a grpc-gateway to multiple gRPC servers
type Gateway struct {
	Context           context.Context
	Handler           []GatewayHandler
	Options           []runtime.ServeMuxOption
	GrpcServerNetwork config.Network
}

// NewGateway returns a pre-initialized gateway.
// You can register as many gRPC services as you like. Just pass in the 'Register<ServiceName>Handler' function
// which is generated by the grpc-gateway plugin
func NewGateway(ctx context.Context, grpcServerNetwork config.Network, handler []GatewayHandler, opts []runtime.ServeMuxOption) *Gateway {
	return &Gateway{
		Context:           ctx,
		Handler:           handler,
		GrpcServerNetwork: grpcServerNetwork,
		Options:           opts,
	}
}

// HttpHandler returns a http.Handler which then can be used in the server to attach it to routing
func (gw *Gateway) HttpHandler() (http.Handler, error) {
	mux := runtime.NewServeMux(gw.Options...)

	client, err := grpc.DialContext(gw.Context, gw.GrpcServerNetwork.Address(), grpc.WithInsecure())
	if err != nil {
		return nil, err
	}

	for _, handler := range gw.Handler {
		if err := handler(gw.Context, mux, client); err != nil {
			return nil, err
		}
	}

	return mux, nil
}

// GatewayServer is a convenience method which returns a pre-initialized http-gateway server
func GatewayServer(grpcNetwork config.Network, handler GatewayHandler) (server *Server, err error) {
	server = NewServer()

	gateway := NewGateway(context.Background(),
		grpcNetwork,
		[]GatewayHandler{handler},
		nil)

	gwHandler, err := gateway.HttpHandler()
	if err != nil {
		return nil, err
	}

	server.AddEndpoint(Endpoint{
		Pattern: "/",
		Handler: gwHandler,
	})

	return server, nil
}
